// Demo marketplace listings — seeded on first load when localStorage is empty
// Uses the exact same schema as publishMarketListing via normalizeProduct

const DEMO_LISTINGS = [
  {
    id: "demo-gameboy-color-berry",
    title: "GameBoy Color - Berry",
    category: "Consoles",
    subCategory: "Game Boy Color",
    condition: "Excellent",
    price: 85,
    description: "Authentic GameBoy Color in Berry finish. Screen is flawless with a new lens. Includes original battery cover. Fully tested and working perfectly.",
    images: ["/images/gameboy.jpg"],
    status: "active",
    seller: "Demo Seller",
    sellerAvatar: "",
    sellerId: "demo-seller",
    parcelSize: "small",
    createdAt: Date.now() - 86400000 * 7,
    publishedAt: Date.now() - 86400000 * 7,
  },
  {
    id: "demo-ps2-slim",
    title: "PlayStation 2 Slim",
    category: "Consoles",
    subCategory: "PlayStation 2",
    condition: "Very Good",
    price: 130,
    description: "PS2 Slim in excellent condition, includes 2 original controllers and AV cables. Console has been cleaned and tested. Minor scratches on the top shell.",
    images: ["/images/ps2.jpg"],
    status: "active",
    seller: "RetroCollector",
    sellerAvatar: "",
    sellerId: "retro-collector",
    parcelSize: "medium",
    createdAt: Date.now() - 86400000 * 5,
    publishedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "demo-n64-atomic-purple",
    title: "Nintendo 64 - Atomic Purple",
    category: "Consoles",
    subCategory: "Nintendo 64",
    condition: "Good",
    price: 95,
    description: "Classic N64 in the iconic Atomic Purple color. Includes expansion pak, one original controller, and power supply. Fully functional.",
    images: ["/images/n64.jpg"],
    status: "active",
    seller: "NostalgiaHunter",
    sellerAvatar: "",
    sellerId: "nostalgia-hunter",
    parcelSize: "medium",
    createdAt: Date.now() - 86400000 * 3,
    publishedAt: Date.now() - 86400000 * 3,
  },
  {
    id: "demo-n64-controller",
    title: "N64 Controller - Atomic Purple",
    category: "Accessories",
    subCategory: "Controllers",
    condition: "Excellent",
    price: 25,
    description: "Official Nintendo 64 controller in Atomic Purple. Joystick is tight and responsive. All buttons work perfectly. Cleaned and tested.",
    images: ["/images/controller.jpg"],
    status: "active",
    seller: "GameEnthusiast",
    sellerAvatar: "",
    sellerId: "game-enthusiast",
    parcelSize: "small",
    createdAt: Date.now() - 86400000 * 2,
    publishedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "demo-sega-genesis",
    title: "Sega Genesis Model 1",
    category: "Consoles",
    subCategory: "Mega Drive/Genesis",
    condition: "Very Good",
    price: 75,
    description: "Original Sega Genesis Model 1 with 'High Definition Graphics' label. Includes one 3-button controller, power adapter, and AV cable. Fully working.",
    images: ["/images/sega.jpg"],
    status: "active",
    seller: "SEGAfanatic",
    sellerAvatar: "",
    sellerId: "sega-fanatic",
    parcelSize: "medium",
    createdAt: Date.now() - 86400000,
    publishedAt: Date.now() - 86400000,
  },
  {
    id: "demo-zelda-ocarina",
    title: "Zelda Ocarina of Time",
    category: "Games",
    subCategory: "Nintendo 64",
    condition: "Excellent",
    price: 45,
    description: "The Legend of Zelda: Ocarina of Time for N64. Gold cartridge collector's edition. Cartridge only, tested and saves perfectly.",
    images: [],
    status: "active",
    seller: "PixelWizard",
    sellerAvatar: "",
    sellerId: "pixel-wizard",
    parcelSize: "small",
    createdAt: Date.now() - 86400000 * 10,
    publishedAt: Date.now() - 86400000 * 10,
  },
];

export default DEMO_LISTINGS;
